# .streamlit/secrets.toml

DEEPSEEK_API_KEY = "sk-57013cf7cd4549e093b8d7e604a52d12"

# Optional: OpenAI API Key for Embeddings (if using OpenAI embeddings)
# Uncomment and replace with your OpenAI API key if needed
OPENAI_API_KEY = "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"